package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.MiaoshaUser;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Mapper
@Component(value = "MiaoshaUserMapper")
public interface MiaoshaUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbggenerated Wed Oct 30 18:48:53 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbggenerated Wed Oct 30 18:48:53 CST 2019
     */
    int insert(MiaoshaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbggenerated Wed Oct 30 18:48:53 CST 2019
     */
    int insertSelective(MiaoshaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbggenerated Wed Oct 30 18:48:53 CST 2019
     */
    MiaoshaUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbggenerated Wed Oct 30 18:48:53 CST 2019
     */
    int updateByPrimaryKeySelective(MiaoshaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbggenerated Wed Oct 30 18:48:53 CST 2019
     */
    int updateByPrimaryKey(MiaoshaUser record);
}