package com.miaoshaproject.dao;


import com.miaoshaproject.dataobject.MiaoshaGoods;

public interface MiaoshaGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbggenerated Wed Oct 30 18:48:53 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbggenerated Wed Oct 30 18:48:53 CST 2019
     */
    int insert(MiaoshaGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbggenerated Wed Oct 30 18:48:53 CST 2019
     */
    int insertSelective(MiaoshaGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbggenerated Wed Oct 30 18:48:53 CST 2019
     */
    MiaoshaGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbggenerated Wed Oct 30 18:48:53 CST 2019
     */
    int updateByPrimaryKeySelective(MiaoshaGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbggenerated Wed Oct 30 18:48:53 CST 2019
     */
    int updateByPrimaryKey(MiaoshaGoods record);
}